# Generated by Django 3.1 on 2021-06-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210601_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_pic',
        ),
    ]
