# Generated by Django 3.1 on 2021-06-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Quntity',
            field=models.IntegerField(blank=True),
        ),
    ]
