# Generated by Django 3.1 on 2021-06-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210601_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Quntity',
        ),
    ]
