# Generated by Django 3.1 on 2021-06-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_order_quntity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
